query GetSeatsQuery($basketId: String!) {
  seats(basketId: $basketId) {
    ...SeatsResponse
  }
}
fragment SeatsResponse on SeatAvailability {
  equipmentModel
  groups {
    fares {
      discount
      originalPrice
      paxNum
      price
    }
    group
    type
  }
  groupsMinPrices {
    available
    fares {
      discount
      originalPrice
      paxNum
      price
    }
    firstRow
    type
  }
  includedSeatRows {
    includedRanges {
      end
      start
    }
    paxNum
  }
  journeyNum
  prmCompanions {
    paxNum
  }
  prmSeats {
    paxNum
    seats
  }
  seatsOffer {
    price
    seats {
      paxNum
      seat
    }
  }
  segmentNum
  unavailableSeats
}
