name: Dagger

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'logic/**'
      - 'cicd/**'
      - 'infra/**'
      - '.github/workflows/**'

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dagger CLI
      run: curl -L https://dl.dagger.io/dagger/install.sh | sh
      working-directory: /usr/local
    - name: Run Dagger
      run: dagger call run \
        --logic="../../logic" \
        --infra="../../infra" \
        --access_key="env:AWS_ACCESS_KEY_ID" \
        --secret_key="env:AWS_SECRET_ACCESS_KEY" \
        --progress="tty"
      working-directory: cicd/dagger
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
