name: Dagger

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'logic/**'
      - 'cicd/**'
      - 'infra/**'
      - '.github/workflows/**'

jobs:
  dagger:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - name: Run dagger
      uses: dagger/dagger-for-github@v5
      with:
        workdir: cicd/dagger
        args: >-
          apply
          --seatchecker="../../logic/seatchecker"
          --notifier="../../logic/notifier"
          --infra="../../infra"
          --access_key="env:SEATCHECKER_AWS_ACCESS_KEY_ID"
          --secret_key="env:SEATCHECKER_AWS_SECRET_ACCESS_KEY"
          --ntfy_topic="env:SEATCHECKER_NTFY_TOPIC"
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      env:
        SEATCHECKER_AWS_ACCESS_KEY_ID: ${{ secrets.SEATCHECKER_AWS_ACCESS_KEY_ID }}
        SEATCHECKER_AWS_SECRET_ACCESS_KEY: ${{ secrets.SEATCHECKER_AWS_SECRET_ACCESS_KEY }}
        SEATCHECKER_NTFY_TOPIC: ${{ secrets.SEATCHECKER_NTFY_TOPIC }}
